"""Build compact RAG-readable cards for LES smeta service sources.

This does not calculate estimates and does not replace the GESN/price parquet
stores. It projects their navigation facts into Markdown so the estimator model
can read them as a small service corpus.
"""

from __future__ import annotations

import argparse
import time
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

from proxy.services import fgis_price_service as fps
from proxy.services.smeta_norm_store import get_smeta_norm_store


DEFAULT_OUT = Path("RAG_Content/TABLE_SMETA/SMETA_SERVICE")
COLLECTION_LIMIT = 30
GENERATED_PATTERNS = (
    "00_smeta_service_overview.md",
    "collection_*.md",
    "pricebook_*.md",
)


def _slug(value: str) -> str:
    out = []
    for char in value.lower():
        if char.isalnum():
            out.append(char)
        elif out and out[-1] != "_":
            out.append("_")
    return "".join(out).strip("_") or "item"


def _csv_list(value: Any) -> list[str]:
    return [part for part in str(value or "").split(",") if part]


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def _clean_generated_cards(out_dir: Path) -> int:
    """Remove only cards generated by this tool before rebuilding the notebook."""
    removed = 0
    for pattern in GENERATED_PATTERNS:
        for path in out_dir.glob(pattern):
            if path.is_file():
                path.unlink()
                removed += 1
    return removed


def _norm_sample(rows: list[Any], *, limit: int = 12) -> list[Any]:
    scored = sorted(
        rows,
        key=lambda r: (
            -int(getattr(r, "resource_count", 0) or 0),
            str(getattr(r, "code", "")),
        ),
    )
    return scored[:limit]


def _collection_cards(out_dir: Path) -> list[dict[str, Any]]:
    store = get_smeta_norm_store()
    by_collection: dict[str, list[Any]] = defaultdict(list)
    for row in store.rows:
        by_collection[str(row.collection_key or "unknown")].append(row)

    cards = []
    for collection, rows in sorted(by_collection.items()):
        families = Counter()
        elements = Counter()
        actions = Counter()
        units = Counter()
        resource_kinds = Counter()
        conditions = Counter()
        for row in rows:
            families.update(_csv_list(row.family_hints))
            elements.update(_csv_list(row.element_hints))
            actions.update(_csv_list(row.action_hints))
            units.update([row.measure_unit or "—"])
            resource_kinds.update(_csv_list(row.resource_kinds))
            conditions.update(_csv_list(row.condition_hints))
        sample = _norm_sample(rows)
        label = sample[0].profile().get("navigation", {}).get("collection", {}).get("label", collection) if sample else collection
        lines = [
            f"# {label}",
            "",
            "Тип: сметный RAG-корпус, карточка сборника ГЭСН/ФЕР/ТЕР.",
            "Назначение: помочь модели выбрать область нормирования и вопросы применимости. Это не готовая смета.",
            "",
            f"- Количество норм в локальной базе: {len(rows)}",
            f"- Семейства работ: {', '.join(k for k, _ in families.most_common(8)) or '—'}",
            f"- Типовые элементы: {', '.join(k for k, _ in elements.most_common(10)) or '—'}",
            f"- Типовые действия: {', '.join(k for k, _ in actions.most_common(8)) or '—'}",
            f"- Измерители норм: {', '.join(k for k, _ in units.most_common(10)) or '—'}",
            f"- Ресурсы в нормах: {', '.join(k for k, _ in resource_kinds.most_common(8)) or '—'}",
            f"- Частые условия применимости: {', '.join(k for k, _ in conditions.most_common(8)) or '—'}",
            "",
            "## Как пользоваться",
            "",
            "- Сначала сопоставь работу с семейством, элементом и действием.",
            "- Потом проверь измеритель нормы и условия применимости.",
            "- Если условия не подтверждены исходником, задай точный сметный вопрос или пометь ценовой/нормативный добор.",
            "- Деньги берутся после раскрытия ресурсов и цен ФГИС/КАЦ/КП; эта карточка сама деньги не доказывает.",
            "",
            "## Примеры норм из локальной базы",
            "",
            "| Код | Наименование | Измеритель | Ресурсов | Что проверить |",
            "|---|---|---:|---:|---|",
        ]
        for row in sample:
            checks = ", ".join(_csv_list(row.condition_hints)[:5]) or "семейство, измеритель, условия"
            title = str(row.title or "").replace("|", "/")
            lines.append(f"| {row.code} | {title[:260]} | {row.measure_unit or '—'} | {row.resource_count} | {checks} |")
        rel = f"collection_{_slug(collection)}.md"
        _write(out_dir / rel, "\n".join(lines))
        cards.append({"collection": collection, "label": label, "norms": len(rows), "file": rel})
    return cards


def _pricebook_cards(out_dir: Path) -> list[dict[str, Any]]:
    cards = []
    for path_text in fps.available_pricebooks():
        path = Path(path_text)
        book = fps.get_pricebook(path_text)
        sample = []
        for query in ("кабель", "бетон", "кран", "рабоч", "металл"):
            for rec in book.search(query, limit=3):
                if rec not in sample:
                    sample.append(rec)
                if len(sample) >= 12:
                    break
            if len(sample) >= 12:
                break
        lines = [
            f"# Ценовая книга ФГИС ЦС: {path.stem}",
            "",
            "Тип: сметный RAG-корпус, карточка ценовой книги ресурсов.",
            "Назначение: помочь модели понимать, какая ценовая база доступна для РИМ и когда нужен КАЦ/КП.",
            "",
            f"- Файл: {path.as_posix()}",
            f"- Регион: {book.region or 'не указан'}",
            f"- Период: {book.quarter or 'не указан'}",
            f"- Строк цен: {len(book)}",
            "",
            "## Правило РИМ",
            "",
            "- Цена ресурса ищется по точному коду ресурса.",
            "- Если есть текущая цена, используется она.",
            "- Если текущей цены нет, используется базовая цена × индекс.",
            "- Если ресурса нет в книге, нужен КАЦ, КП, прайс или ручная цена с provenance.",
            "",
            "## Примеры строк",
            "",
            "| Код ресурса | Наименование | Ед. | Текущая цена/эффективная | Группа/индекс |",
            "|---|---|---:|---:|---|",
        ]
        for rec in sample:
            name = str(rec.get("name") or "").replace("|", "/")
            group = str(rec.get("group_name") or rec.get("group_no") or "").replace("|", "/")
            lines.append(
                f"| {rec.get('code') or '—'} | {name[:260]} | {rec.get('unit') or '—'} "
                f"| {rec.get('price_current_eff') or '—'} | {group[:160]} / индекс {rec.get('index') or '—'} |"
            )
        rel = f"pricebook_{_slug(path.stem)}.md"
        _write(out_dir / rel, "\n".join(lines))
        cards.append({"book": path.stem, "region": book.region, "quarter": book.quarter, "rows": len(book), "file": rel})
    return cards


def build(out_dir: Path = DEFAULT_OUT) -> dict[str, Any]:
    out_dir.mkdir(parents=True, exist_ok=True)
    removed_cards = _clean_generated_cards(out_dir)
    collection_cards = _collection_cards(out_dir)
    price_cards = _pricebook_cards(out_dir)
    store = get_smeta_norm_store()
    payload = store.payload()
    lines = [
        "# Сметный служебный RAG-корпус ЛЕС",
        "",
        "Это компактная карта локальных сметных источников: ГЭСН/РИМ-нормы, ресурсы и ценовые книги.",
        "Корпус нужен модели-сметчику как читаемая навигация. Он не является готовой сметой и не заменяет расчётную трассу.",
        "",
        f"- Норм в локальной базе: {payload.get('norm_count')}",
        f"- Коллекций/сборников: {payload.get('collections')}",
        f"- Видимых ценовых книг: {len(price_cards)}",
        f"- Обновлено: {time.strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "## Как отвечать в режиме Смета",
        "",
        "- Модель читает исходник, собирает ВОР и выбирает нормативный/ценовой ход.",
        "- ГЭСН-карточки помогают выбрать сборник, измеритель и вопросы применимости.",
        "- Ценовые книги помогают понять, что может быть рассчитано по РИМ, а где нужен КАЦ/КП/прайс.",
        "- Если часть работ/цен не закрыта, показывай рассчитанную или сценарную часть отдельно от полного итога.",
        "",
        "## Карточки сборников",
        "",
    ]
    for card in collection_cards:
        lines.append(f"- [{card['label']}]({card['file']}) — {card['norms']} норм")
    lines += ["", "## Карточки ценовых книг", ""]
    for card in price_cards:
        lines.append(f"- [{card['book']}]({card['file']}) — {card['rows']} строк; {card.get('region') or 'регион не указан'} {card.get('quarter') or ''}".strip())
    _write(out_dir / "00_smeta_service_overview.md", "\n".join(lines))
    return {
        "out_dir": out_dir.as_posix(),
        "removed_cards": removed_cards,
        "collection_cards": len(collection_cards),
        "price_cards": len(price_cards),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="Output folder under RAG_Content")
    args = parser.parse_args()
    result = build(Path(args.out))
    print(result)


if __name__ == "__main__":
    main()
